Repository hpi-swa-teaching/PrettyPrettyPrint, pull requests merged in 2019-05, with the labels that each got.

#34 Fixed "dot after pragma"-bug
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNoDotAfterPragma.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPDummi.class/instance/cascadeBug..st
  packages/PrettyPrettyPrint.package/PPPDummi.class/instance/testMessage.st
  packages/PrettyPrettyPrint.package/PPPDummi.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPNode.class/instance/isPragmaNode.st
  packages/PrettyPrettyPrint.package/PPPNode.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPPragmaNode.class/instance/isPragmaNode.st
  packages/PrettyPrettyPrint.package/PPPPragmaNode.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/printStatementsOf.on..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNoDotAfterPragma.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/monticello.meta/categories.st
Labels: bug

#35 Us help browser documentation
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNewlineAfterSelector.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testSpaceAroundBinaryOperator.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPHelp.class/README.md
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/bookName.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/introduction.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/pages.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/pragmaFirstExample.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/pragmaIntroduction.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/pragmaPattern.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/pragmaSecondExample.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/pragmaSupportedRules.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/class/usingPragmas.st
  packages/PrettyPrettyPrint.package/PPPHelp.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPHelp.class/properties.json
  packages/PrettyPrettyPrint.package/PPPPrinter.class/class/format.preferences..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/initialize.st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/printStatementsOf.on..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/visitMethodNode..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNewlineAfterSelector.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testSpaceAroundBinaryOperator.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/class/newlineAfterSelector..st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/class/newlineAfterSelector.st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/class/spaceAroundBinaryOperator..st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/class/spaceAroundBinaryOperator.st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/class/userProfile.st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/instance/initialize.st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/instance/newlineAfterSelector..st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/instance/newlineAfterSelector.st
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPSettingsProfile.class/properties.json
  packages/PrettyPrettyPrint.package/monticello.meta/categories.st
Labels: documentation, new feature, refactoring, user story

#39 Added option to add a newline before a return statement
  packages/PrettyPrettyPrint-Tests.package/PPPParserTests.class/instance/testParseBinaryMessageDeclaration.st
  packages/PrettyPrettyPrint-Tests.package/PPPParserTests.class/methodProperties.json
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testComments.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testKeepEmptyLines.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNewlineAfterSelector.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNewlineAfterSelectorWithKeepEmptyLines.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNewlineAfterSelectorWithNewlineBeforeReturn.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNewlineBeforeReturn.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testNewlineBeforeReturnWithKeepEmptyLines.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintArray.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintBlock.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintComplexBlocks.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintMethodNode.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintMultilineMessage.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintPragma.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintReturnNode.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintSequenceNode.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/instance/testPrintShortNamedMessage.st
  packages/PrettyPrettyPrint-Tests.package/PPPPrinterTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPNode.class/instance/isReturnNode.st
  packages/PrettyPrettyPrint.package/PPPNode.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPParserTests.class/instance/testParseBinaryMessageDeclaration.st
  packages/PrettyPrettyPrint.package/PPPParserTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/newLineAfterSelectorNeededFor..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/newLineNeededBefore.of..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/printCommentsOf.on..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/printStatementsOf.on..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/instance/visitMethodNode..st
  packages/PrettyPrettyPrint.package/PPPPrinter.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testComments.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testKeepEmptyLines.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNewlineAfterSelector.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNewlineAfterSelectorWithKeepEmptyLines.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNewlineAfterSelectorWithNewlineBeforeReturn.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNewlineBeforeReturn.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testNewlineBeforeReturnWithKeepEmptyLines.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintArray.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintBlock.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintComplexBlocks.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintMethodNode.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintMultilineMessage.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintPragma.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintReturnNode.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintSequenceNode.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/instance/testPrintShortNamedMessage.st
  packages/PrettyPrettyPrint.package/PPPPrinterTests.class/methodProperties.json
  packages/PrettyPrettyPrint.package/PPPReturnNode.class/instance/isReturnNode.st
  packages/PrettyPrettyPrint.package/PPPReturnNode.class/methodProperties.json
Labels: configuration, new feature, user story
